var exports = module.exports = {};

exports.errorSection = function() {
    return {
        "eg": "1",
        "et": 4,
        "eu": "0://1/2/3/4",
        "ts": 1520880072683,
        "mg": "0",
        "au": "0://1/5",
        "at": 0,
        "dm": "Uncaught Error: [$injector:modulerr] Failed to instantiate module ADFinApp due to:\nError: [$injector:nomod] Module 'ADFinApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.\nhttp://errors.angularjs.org/1.5.11/$injector/nomod?p0=ADFinApp\n    at http://adfin.com/bower_components/angular/angular.js:68:12\n    at http://adfin.com/bower_components/angular/angular.js:2133:17\n    at ensure (http://adfin.com/bower_components/angular/angular.js:2057:38)\n    at module (http://adfin.com/bower_components/angular/angular.js:2131:14)\n    at http://adfin.com/bower_components/angular/angular.js:4669:22\n    at forEach (http://adfin.com/bower_components/angular/angular.js:325:20)\n    at loadModules (http://adfin.com/bower_components/angular/angular.js:4653:5)\n    at createInjector (http://adfin.com/bower_components/angular/angular.js:4575:19)\n    at doBootstrap (http://adfin.com/bower_components/angular/angular.js:1809:20)\n    at bootstrap (http://adfin.com/bower_components/angular/angular.js:1830:12)\nhttp://errors.angularjs.org/1.5.11/$injector/modulerr?p0=ADFinApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ADFinApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DADFinApp%0A%20%20%20%20at%20http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2057%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2131%3A1",
        "ln": 68,
        "stack": "Error: [$injector:modulerr] Failed to instantiate module ADFinApp due to:\nError: [$injector:nomod] Module 'ADFinApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.\nhttp://errors.angularjs.org/1.5.11/$injector/nomod?p0=ADFinApp\n    at http://adfin.com/bower_components/angular/angular.js:68:12\n    at http://adfin.com/bower_components/angular/angular.js:2133:17\n    at ensure (http://adfin.com/bower_components/angular/angular.js:2057:38)\n    at module (http://adfin.com/bower_components/angular/angular.js:2131:14)\n    at http://adfin.com/bower_components/angular/angular.js:4669:22\n    at forEach (http://adfin.com/bower_components/angular/angular.js:325:20)\n    at loadModules (http://adfin.com/bower_components/angular/angular.js:4653:5)\n    at createInjector (http://adfin.com/bower_components/angular/angular.js:4575:19)\n    at doBootstrap (http://adfin.com/bower_components/angular/angular.js:1809:20)\n    at bootstrap (http://adfin.com/bower_components/angular/angular.js:1830:12)\nhttp://errors.angularjs.org/1.5.11/$injector/modulerr?p0=ADFinApp&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'ADFinApp'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.11%2F%24injector%2Fnomod%3Fp0%3DADFinApp%0A%20%20%20%20at%20http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A68%3A12%0A%20%20%20%20at%20http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2133%3A17%0A%20%20%20%20at%20ensure%20(http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2057%3A38)%0A%20%20%20%20at%20module%20(http%3A%2F%2Fadfin.com%2Fbower_components%2Fangular%2Fangular.js%3A2131%3A14)%0A%20%",
        "si": 4216
    };
}

exports.standardBeacon = function() {
    return {
    "vr": "4.3.3.0",
    "dt": "R",
    "rg": "0",
    "es":[
        {
            "eg":"0",
            "et":0,
            "eu":"0://1/2",
            "ts":1456349692230,
            "mc":{
                "PLT":365,
                "FBT":94,
                "FET":271,
                "DRT":50,
                "PRT":221,
                "DOM":144,
                "ts":1456349692228,
                "PLC":1
            },
            "mx":{
                "PLT":364,
                "FBT":78,
                "SCT":15,
                "DLT":22,
                "TCP":38,
                "RAT":63,
                "FET":286,
                "DRT":67,
                "DDT":40,
                "DPT":27,
                "PRT":219,
                "DOM":145,
                "ts":1456349692230,
                "PLC":1
            },
            "pl":"Login",
            "sm":{
                "cg":"0",
                "btgan":"customer1_f16aea9b-844d-476d-92db-60f3acaa620d",
                "bt":[
                    {
                        "id":"22",
                        "dn":6,
                        "ert":7
                    }
                ]
            },
            "rt":{
                "v":2,
                "ic":{
                    "other":1,
                    "script":2,
                    "link":1,
                    "img":17,
                    "css":1,
                    "xmlhttprequest":1
                },
                "it":{
                    "other":1,
                    "script":2,
                    "link":3,
                    "img":4,
                    "css":5,
                    "xmlhttprequest":6
                },
                "rc":{
                    "other":2,
                    "script":2,
                    "css":1,
                    "img":18
                },
                "rt":{
                    "other":1,
                    "script":2,
                    "css":3,
                    "img":4
                },
                "f":{
                    "1":[
                        "startTime",
                        "redirectStart",
                        "redirectEnd",
                        "fetchStart",
                        "dnsLookupStart",
                        "dnsLookupEnd",
                        "connectStart",
                        "connectEnd",
                        "requestStart",
                        "responseStart",
                        "responseEnd"
                    ],
                    "2":[
                        "startTime",
                        "fetchStart",
                        "responseEnd"
                    ]
                },
                "t":1456349692230,
                "r":[
                    {
                        "u":"0://7/2/",
                        "i":1,
                        "r":1,
                        "f":1,
                        "o":1,
                        "m":[
                            0,
                            -1,
                            -1,
                            3,
                            3,
                            3,
                            3,
                            3,
                            4,
                            78,
                            118
                        ]
                    },
                    {
                        "u":"0://7/8",
                        "i":2,
                        "r":2,
                        "f":1,
                        "o":94,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/9/10",
                        "i":3,
                        "r":3,
                        "f":1,
                        "o":94,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://11/12/13/14/15/16",
                        "i":2,
                        "r":2,
                        "f":1,
                        "o":94,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            2,
                            3,
                            5
                        ]
                    },
                    {
                        "u":"0://7/2/17/18",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":94,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/19",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":110,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/20",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":110,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/21",
                        "i":5,
                        "r":4,
                        "f":1,
                        "o":142,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/22",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":144,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            3,
                            214,
                            216
                        ]
                    },
                    {
                        "u":"0://7/2/3/4/5?6",
                        "i":6,
                        "r":1,
                        "f":1,
                        "o":152,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            3,
                            57,
                            59
                        ]
                    },
                    {
                        "u":"0://7/2/17/23",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":216,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/24",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":219,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/25",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":220,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/26",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":221,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/27",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":222,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/28",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":224,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/29",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":225,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/30",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":226,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/31",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":228,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/32",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":229,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/33",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":230,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/34",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":231,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    },
                    {
                        "u":"0://7/2/17/35",
                        "i":4,
                        "r":4,
                        "f":1,
                        "o":232,
                        "m":[
                            0,
                            -1,
                            -1,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0,
                            0
                        ]
                    }
                ]
            },
            "si":0
        }
    ],
    "ai": "ca8ea7e1_2557_b376_ff31_bb388db7499e",
    "gs": [],
    "up": [
        "http",
        "www.acme-financial.com",
        "home",
        "styles",
        "bootstrap.css",
        "animations.css",
        "styles.css",
        "node_modules",
        "angular-material",
        "angular-material.css",
        "angular",
        "angular.js",
        "angular-animate",
        "angular-animate.js",
        "angular-route",
        "angular-route.js",
        "images",
        "logo.png",
        "shoppingcart.png",
        "angular-ui-bootstrap",
        "dist",
        "ui-bootstrap.js",
        "angular-material.js",
        "angular-aria",
        "angular-aria.js",
        "scripts",
        "mask.js",
        "app.js",
        "index",
        "indexController.js",
        "login",
        "loginController.js",
        "homeController.js",
        "shop",
        "shopController.js",
        "deals",
        "dealsController.js",
        "myAccount",
        "myAccountController.js",
        "updateAccount",
        "updateAccountController.js",
        "checkout",
        "checkoutController.js",
        "services",
        "config.js",
        "authService.js",
        "httpInterceptors.js",
        "animations",
        "listAnimations.js",
        "directives",
        "wcOverlay.js",
        "menuHighlighter.js",
        "adrum",
        "adrum.js"
    ]
};
}
